config/routes.rb
WishWall::Application.routes.draw do
  resources :wishwalls

  resources :wishes

  root to: "wishwalls#index"

end

app/models/wish.rb
class Wish < ActiveRecord::Base
  attr_accessible :mywish
end

app/models/wishwall.rb
class Wishwall < ActiveRecord::Base
  attr_accessible :wish
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  # GET /wishes
  # GET /wishes.json
  def index
    @wishes = Wish.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wishes }
    end
  end

  # GET /wishes/1
  # GET /wishes/1.json
  def show
    @wish = Wish.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wish }
    end
  end

  # GET /wishes/new
  # GET /wishes/new.json
  def new
    @wish = Wish.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wish }
    end
  end

  # GET /wishes/1/edit
  def edit
    @wish = Wish.find(params[:id])
  end

  # POST /wishes
  # POST /wishes.json
  def create
    @wish = Wish.new(params[:wish])

    respond_to do |format|
      if @wish.save
        format.html { redirect_to @wish, notice: 'Wish was successfully created.' }
        format.json { render json: @wish, status: :created, location: @wish }
      else
        format.html { render action: "new" }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wishes/1
  # PUT /wishes/1.json
  def update
    @wish = Wish.find(params[:id])

    respond_to do |format|
      if @wish.update_attributes(params[:wish])
        format.html { redirect_to @wish, notice: 'Wish was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishes/1
  # DELETE /wishes/1.json
  def destroy
    @wish = Wish.find(params[:id])
    @wish.destroy

    respond_to do |format|
      format.html { redirect_to wishes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/wishwalls_controller.rb
class WishwallsController < ApplicationController
  # GET /wishwalls
  # GET /wishwalls.json
  def index
    @wishwalls = Wishwall.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wishwalls }
    end
  end

  # GET /wishwalls/1
  # GET /wishwalls/1.json
  def show
    @wishwall = Wishwall.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wishwall }
    end
  end

  # GET /wishwalls/new
  # GET /wishwalls/new.json
  def new
    @wishwall = Wishwall.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wishwall }
    end
  end

  # GET /wishwalls/1/edit
  def edit
    @wishwall = Wishwall.find(params[:id])
  end

  # POST /wishwalls
  # POST /wishwalls.json
  def create
    @wishwall = Wishwall.new(params[:wishwall])

    respond_to do |format|
      if @wishwall.save
        format.html { redirect_to @wishwall, notice: 'Wishwall was successfully created.' }
        format.json { render json: @wishwall, status: :created, location: @wishwall }
      else
        format.html { render action: "new" }
        format.json { render json: @wishwall.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wishwalls/1
  # PUT /wishwalls/1.json
  def update
    @wishwall = Wishwall.find(params[:id])

    respond_to do |format|
      if @wishwall.update_attributes(params[:wishwall])
        format.html { redirect_to @wishwall, notice: 'Wishwall was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wishwall.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishwalls/1
  # DELETE /wishwalls/1.json
  def destroy
    @wishwall = Wishwall.find(params[:id])
    @wishwall.destroy

    respond_to do |format|
      format.html { redirect_to wishwalls_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/helpers/wishwalls_helper.rb
module WishwallsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WishWall</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/wishes/_form.html.erb
<%= form_for(@wish) do |f| %>
  <% if @wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
      <% @wish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mywish %><br />
    <%= f.text_field :mywish %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishes/edit.html.erb
<h1>Editing wish</h1>

<%= render 'form' %>

<%= link_to 'Show', @wish %> |
<%= link_to 'Back', wishes_path %>

app/views/wishes/index.html.erb
<h1 class="title" >Wish Wall</h1>


<% @wishes.each do |wish| %>

   <%= wish.mywish %>  &nbsp; &nbsp;&nbsp;

<% end %>


<br />      <br />     <br />      <br />

<div class="addWish">
<%= link_to 'New Wish', new_wish_path %>
</div>

app/views/wishes/new.html.erb
<h1>New wish</h1>

<%= render 'form' %>

<%= link_to 'Back', wishes_path %>

app/views/wishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Mywish:</b>
  <%= @wish.mywish %>
</p>


<%= link_to 'Edit', edit_wish_path(@wish) %> |
<%= link_to 'Back', wishes_path %>

app/views/wishwalls/_form.html.erb
<%= form_for(@wishwall) do |f| %>
  <% if @wishwall.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wishwall.errors.count, "error") %> prohibited this wishwall from being saved:</h2>

      <ul>
      <% @wishwall.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :wish %><br />
    <%= f.text_field :wish %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishwalls/edit.html.erb
<h1>Editing wishwall</h1>

<%= render 'form' %>

<%= link_to 'Show', @wishwall %> |
<%= link_to 'Back', wishwalls_path %>

app/views/wishwalls/index.html.erb
<h1>Listing wishwalls</h1>

<table>
  <tr>
    <th>Wish</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wishwalls.each do |wishwall| %>
  <tr>
    <td><%= wishwall.wish %></td>
    <td><%= link_to 'Show', wishwall %></td>
    <td><%= link_to 'Edit', edit_wishwall_path(wishwall) %></td>
    <td><%= link_to 'Destroy', wishwall, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wishwall', new_wishwall_path %>

app/views/wishwalls/new.html.erb
<h1>New wishwall</h1>

<%= render 'form' %>

<%= link_to 'Back', wishwalls_path %>

app/views/wishwalls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Wish:</b>
  <%= @wishwall.wish %>
</p>


<%= link_to 'Edit', edit_wishwall_path(@wishwall) %> |
<%= link_to 'Back', wishwalls_path %>